// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: internal/application/adapter/grpc/get_file_metadata.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileMetadataService_GetFileMetadata_FullMethodName = "/proto.FileMetadataService/GetFileMetadata"
)

// FileMetadataServiceClient is the client API for FileMetadataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileMetadataServiceClient interface {
	GetFileMetadata(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[GetFileMetadataRequest, GetFileMetadataResponse], error)
}

type fileMetadataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileMetadataServiceClient(cc grpc.ClientConnInterface) FileMetadataServiceClient {
	return &fileMetadataServiceClient{cc}
}

func (c *fileMetadataServiceClient) GetFileMetadata(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[GetFileMetadataRequest, GetFileMetadataResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FileMetadataService_ServiceDesc.Streams[0], FileMetadataService_GetFileMetadata_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetFileMetadataRequest, GetFileMetadataResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileMetadataService_GetFileMetadataClient = grpc.ClientStreamingClient[GetFileMetadataRequest, GetFileMetadataResponse]

// FileMetadataServiceServer is the server API for FileMetadataService service.
// All implementations must embed UnimplementedFileMetadataServiceServer
// for forward compatibility.
type FileMetadataServiceServer interface {
	GetFileMetadata(grpc.ClientStreamingServer[GetFileMetadataRequest, GetFileMetadataResponse]) error
	mustEmbedUnimplementedFileMetadataServiceServer()
}

// UnimplementedFileMetadataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileMetadataServiceServer struct{}

func (UnimplementedFileMetadataServiceServer) GetFileMetadata(grpc.ClientStreamingServer[GetFileMetadataRequest, GetFileMetadataResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetFileMetadata not implemented")
}
func (UnimplementedFileMetadataServiceServer) mustEmbedUnimplementedFileMetadataServiceServer() {}
func (UnimplementedFileMetadataServiceServer) testEmbeddedByValue()                             {}

// UnsafeFileMetadataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileMetadataServiceServer will
// result in compilation errors.
type UnsafeFileMetadataServiceServer interface {
	mustEmbedUnimplementedFileMetadataServiceServer()
}

func RegisterFileMetadataServiceServer(s grpc.ServiceRegistrar, srv FileMetadataServiceServer) {
	// If the following call pancis, it indicates UnimplementedFileMetadataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileMetadataService_ServiceDesc, srv)
}

func _FileMetadataService_GetFileMetadata_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FileMetadataServiceServer).GetFileMetadata(&grpc.GenericServerStream[GetFileMetadataRequest, GetFileMetadataResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileMetadataService_GetFileMetadataServer = grpc.ClientStreamingServer[GetFileMetadataRequest, GetFileMetadataResponse]

// FileMetadataService_ServiceDesc is the grpc.ServiceDesc for FileMetadataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileMetadataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.FileMetadataService",
	HandlerType: (*FileMetadataServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetFileMetadata",
			Handler:       _FileMetadataService_GetFileMetadata_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "internal/application/adapter/grpc/get_file_metadata.proto",
}
