app:
  name: "gopherFS-storage-service"
  version: "0.0.1"

kafka:
  brokers: ["kafka:9092"]
  topic_file_metadata_save: "emit-file-metadata-save"
  topic_file_metadata_read: "emit-file-metadata-read"
  topic_file_metadata_delete: "emit-file-metadata-delete"

etcd:
  endpoints: ["etcd:2379"]
  dial_timeout: 10
  ttl: 30

log:
  log_level: "debug"

grpc:
  port: ":50050"
