// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.21.12
// source: internal/application/adapter/grpc/file_chunk_download.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileChunkDownloadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileId         string `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	SequenceNumber uint32 `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
}

func (x *FileChunkDownloadRequest) Reset() {
	*x = FileChunkDownloadRequest{}
	mi := &file_internal_application_adapter_grpc_file_chunk_download_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunkDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunkDownloadRequest) ProtoMessage() {}

func (x *FileChunkDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_application_adapter_grpc_file_chunk_download_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunkDownloadRequest.ProtoReflect.Descriptor instead.
func (*FileChunkDownloadRequest) Descriptor() ([]byte, []int) {
	return file_internal_application_adapter_grpc_file_chunk_download_proto_rawDescGZIP(), []int{0}
}

func (x *FileChunkDownloadRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileChunkDownloadRequest) GetSequenceNumber() uint32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

type FileChunkDownloadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileId         string `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	SequenceNumber uint32 `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Chunk          []byte `protobuf:"bytes,3,opt,name=chunk,proto3" json:"chunk,omitempty"`
}

func (x *FileChunkDownloadResponse) Reset() {
	*x = FileChunkDownloadResponse{}
	mi := &file_internal_application_adapter_grpc_file_chunk_download_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunkDownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunkDownloadResponse) ProtoMessage() {}

func (x *FileChunkDownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_application_adapter_grpc_file_chunk_download_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunkDownloadResponse.ProtoReflect.Descriptor instead.
func (*FileChunkDownloadResponse) Descriptor() ([]byte, []int) {
	return file_internal_application_adapter_grpc_file_chunk_download_proto_rawDescGZIP(), []int{1}
}

func (x *FileChunkDownloadResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileChunkDownloadResponse) GetSequenceNumber() uint32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *FileChunkDownloadResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

var File_internal_application_adapter_grpc_file_chunk_download_proto protoreflect.FileDescriptor

var file_internal_application_adapter_grpc_file_chunk_download_proto_rawDesc = []byte{
	0x0a, 0x3b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x64,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5c, 0x0a, 0x18, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e,
	0x6b, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x65, 0x71,
	0x75, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0e, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x22, 0x73, 0x0a, 0x19, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x44,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x17, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x65, 0x71, 0x75,
	0x65, 0x6e, 0x63, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0e, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x32, 0x70, 0x0a, 0x18, 0x46, 0x69, 0x6c, 0x65, 0x43,
	0x68, 0x75, 0x6e, 0x6b, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x54, 0x0a, 0x0d, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x43,
	0x68, 0x75, 0x6e, 0x6b, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x69, 0x6c,
	0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x69,
	0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x3b,
	0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_application_adapter_grpc_file_chunk_download_proto_rawDescOnce sync.Once
	file_internal_application_adapter_grpc_file_chunk_download_proto_rawDescData = file_internal_application_adapter_grpc_file_chunk_download_proto_rawDesc
)

func file_internal_application_adapter_grpc_file_chunk_download_proto_rawDescGZIP() []byte {
	file_internal_application_adapter_grpc_file_chunk_download_proto_rawDescOnce.Do(func() {
		file_internal_application_adapter_grpc_file_chunk_download_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_application_adapter_grpc_file_chunk_download_proto_rawDescData)
	})
	return file_internal_application_adapter_grpc_file_chunk_download_proto_rawDescData
}

var file_internal_application_adapter_grpc_file_chunk_download_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_application_adapter_grpc_file_chunk_download_proto_goTypes = []any{
	(*FileChunkDownloadRequest)(nil),  // 0: proto.FileChunkDownloadRequest
	(*FileChunkDownloadResponse)(nil), // 1: proto.FileChunkDownloadResponse
}
var file_internal_application_adapter_grpc_file_chunk_download_proto_depIdxs = []int32{
	0, // 0: proto.FileChunkDownloadService.DownloadChunk:input_type -> proto.FileChunkDownloadRequest
	1, // 1: proto.FileChunkDownloadService.DownloadChunk:output_type -> proto.FileChunkDownloadResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_application_adapter_grpc_file_chunk_download_proto_init() }
func file_internal_application_adapter_grpc_file_chunk_download_proto_init() {
	if File_internal_application_adapter_grpc_file_chunk_download_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_application_adapter_grpc_file_chunk_download_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_application_adapter_grpc_file_chunk_download_proto_goTypes,
		DependencyIndexes: file_internal_application_adapter_grpc_file_chunk_download_proto_depIdxs,
		MessageInfos:      file_internal_application_adapter_grpc_file_chunk_download_proto_msgTypes,
	}.Build()
	File_internal_application_adapter_grpc_file_chunk_download_proto = out.File
	file_internal_application_adapter_grpc_file_chunk_download_proto_rawDesc = nil
	file_internal_application_adapter_grpc_file_chunk_download_proto_goTypes = nil
	file_internal_application_adapter_grpc_file_chunk_download_proto_depIdxs = nil
}
